ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS buy_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sell_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rent_count INTEGER NOT NULL DEFAULT 0;